import { Schema, model, type HydratedDocument, type Types } from "mongoose";

// Five statuses and four priorities, from 03-DESIGN-REFERENCE.md rather than
// the three and three the brief suggests. The design file calls itself the
// source of truth and the brief calls its own list "suggested".
// See docs/decisions/0005-five-statuses-four-priorities.md.
export const TASK_STATUSES = [
  "todo",
  "in_progress",
  "in_review",
  "done",
  "blocked",
] as const;

export const TASK_PRIORITIES = ["low", "medium", "high", "urgent"] as const;

export type TaskStatus = (typeof TASK_STATUSES)[number];
export type TaskPriority = (typeof TASK_PRIORITIES)[number];

export interface Task {
  // The short readable id from the design: TF-118. Generated by the counter,
  // never taken from the request.
  key: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  dueDate?: Date | null;
  // The assignee's id, not a copy of the assignee. One place holds the truth
  // about a person's name, so changing it shows up on every task at once.
  assigneeId?: Types.ObjectId | null;
  creatorId: Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

export type TaskDocument = HydratedDocument<Task>;

const taskSchema = new Schema<Task>(
  {
    key: {
      type: String,
      required: true,
      unique: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
      minlength: 1,
      maxlength: 200,
    },
    description: {
      type: String,
      default: "",
      trim: true,
      maxlength: 5000,
    },
    status: {
      type: String,
      enum: TASK_STATUSES,
      default: "todo",
      required: true,
    },
    priority: {
      type: String,
      enum: TASK_PRIORITIES,
      default: "medium",
      required: true,
    },
    dueDate: {
      type: Date,
      default: null,
    },
    assigneeId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    creatorId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  {
    timestamps: true,
    toJSON: {
      transform(_doc, ret: Record<string, unknown>) {
        delete ret.__v;
        return ret;
      },
    },
  },
);

// Only the index this version needs. The compound {status, priority, updatedAt}
// index and the ones on assigneeId and dueDate exist to make *queries* fast,
// and there is no query route until V4.

export const TaskModel = model<Task>("Task", taskSchema);
