import { Schema, model, type HydratedDocument, type Types } from "mongoose";

// Five statuses and four priorities, from 03-DESIGN-REFERENCE.md rather than
// the three and three the brief suggests. The design file calls itself the
// source of truth and the brief calls its own list "suggested".
// See docs/decisions/0005-five-statuses-four-priorities.md.
export const TASK_STATUSES = [
  "todo",
  "in_progress",
  "in_review",
  "done",
  "blocked",
] as const;

// Listed lowest first. The order of this array IS the priority order, and it
// is the only place that order is written down — PRIORITY_RANK below is
// derived from it, so the two can never disagree.
export const TASK_PRIORITIES = ["low", "medium", "high", "urgent"] as const;

export type TaskStatus = (typeof TASK_STATUSES)[number];
export type TaskPriority = (typeof TASK_PRIORITIES)[number];

// low: 1, medium: 2, high: 3, urgent: 4.
export const PRIORITY_RANK: Record<TaskPriority, number> = Object.fromEntries(
  TASK_PRIORITIES.map((priority, index) => [priority, index + 1]),
) as Record<TaskPriority, number>;

export interface Task {
  // The short readable id from the design: TF-118. Generated by the counter,
  // never taken from the request.
  key: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  // The same value as `priority`, as a number, so sorting works. Sorting the
  // words alphabetically would give high, low, medium, urgent — meaningless.
  // Kept in step by the hook below; never set by hand and never accepted from
  // a request. See docs/decisions/0007-priority-rank.md.
  priorityRank: number;
  dueDate?: Date | null;
  // The assignee's id, not a copy of the assignee. One place holds the truth
  // about a person's name, so changing it shows up on every task at once.
  assigneeId?: Types.ObjectId | null;
  creatorId: Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

export type TaskDocument = HydratedDocument<Task>;

const taskSchema = new Schema<Task>(
  {
    key: {
      type: String,
      required: true,
      unique: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
      minlength: 1,
      maxlength: 200,
    },
    description: {
      type: String,
      default: "",
      trim: true,
      maxlength: 5000,
    },
    status: {
      type: String,
      enum: TASK_STATUSES,
      default: "todo",
      required: true,
    },
    priority: {
      type: String,
      enum: TASK_PRIORITIES,
      default: "medium",
      required: true,
    },
    priorityRank: {
      type: Number,
      required: true,
      default: PRIORITY_RANK.medium,
    },
    dueDate: {
      type: Date,
      default: null,
    },
    assigneeId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    creatorId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  {
    timestamps: true,
    toJSON: {
      transform(_doc, ret: Record<string, unknown>) {
        delete ret.__v;
        return ret;
      },
    },
  },
);

// Keeps priorityRank in step with priority in ONE place. Runs on create and on
// every save, so the two cannot drift apart.
taskSchema.pre("validate", function syncPriorityRank() {
  if (this.isModified("priority") || this.isNew) {
    this.priorityRank = PRIORITY_RANK[this.priority] ?? PRIORITY_RANK.medium;
  }
});

// findOneAndUpdate skips document hooks entirely — it talks to the database
// without building a document — so the same rule is applied again here. Missing
// this is how a task edited to "urgent" would keep sorting as "medium".
taskSchema.pre("findOneAndUpdate", function syncPriorityRankOnUpdate() {
  const update = this.getUpdate() as Record<string, unknown> | null;
  const priority = update?.priority as TaskPriority | undefined;

  if (priority && priority in PRIORITY_RANK) {
    this.setUpdate({ ...update, priorityRank: PRIORITY_RANK[priority] });
  }
});

// An index is a sorted lookup list kept beside the data, so the database can
// jump straight to matches instead of reading every record.
//
// A combined index works left to right, like a phone book sorted by surname
// then first name: "everyone called Kumar" and "Kumar, A" are both fast,
// "everyone called A" is not. That is why the order below is the order the
// list screen actually filters in.
taskSchema.index({ status: 1, priority: 1, updatedAt: -1 });
taskSchema.index({ assigneeId: 1 });
taskSchema.index({ dueDate: 1 });
taskSchema.index({ priorityRank: -1 });

export const TaskModel = model<Task>("Task", taskSchema);
